name: build

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:    
       - name: 正在初始化
         run: |
              sudo -E apt-get -qq install git
       
       - name: 正在拉取代码
         run: |
              cd $GITHUB_WORKSPACE
              sudo git clone -b test --depth 1 https://gitee.com/hais/HaisV3.git HaisV3
           
       - name: 正在安装依赖
         run: |
              cd $GITHUB_WORKSPACE
              sudo ./HaisV3/Bin/0.Install.sh
              
       - name: 开始全自动做包并上传
         run: |
             cd $GITHUB_WORKSPACE
             sudo ./HaisV3/Bin/1.Start.sh 'https://bigota.d.miui.com/V12.5.1.0.QDTCNXM/miui_MI8Lite_V12.5.1.0.QDTCNXM_c02c6bcfb0_10.0.zip' 
                  

              

       - name: Upload to WeTransfer

         run: |

              cd $GITHUB_WORKSPACE/HaisV3

              curl -sL https://git.io/file-transfer | sh

              ./transfer wet ./Test/*
name: build

on:
  watch:
    types: [started]
    
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:    
       - name: 正在初始化
         run: |
              sudo -E apt-get -qq install git
       
       - name: 正在拉取代码
         run: |
              cd $GITHUB_WORKSPACE
              sudo git clone -b test --depth 1 https://gitee.com/hais/HaisV3.git HaisV3
           
       - name: 正在安装依赖
         run: |
              cd $GITHUB_WORKSPACE
              sudo ./HaisV3/Bin/0.Install.sh
              
       - name: 开始全自动做包
         run: |
             cd $GITHUB_WORKSPACE
             sudo ./HaisV3/Bin/1.Start.sh 'https://bigota.d.miui.com/V12.5.1.0.QDTCNXM/miui_MI8Lite_V12.5.1.0.QDTCNXM_c02c6bcfb0_10.0.zip' 
      
       - name: 开始上传ROM
         run: |
             cd ${GITHUB_WORKSPACE}/HaisV3/Test
             ROM_NAME=`find ./*.zip -type f | head -1`
             curl --upload-file ./$ROM_NAME  https://transfer.sh/${ROM_NAME##*/}
           
            
